// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: workspace/v1/registration.proto

package workspacev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RedeemTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeemTokenRequest) Reset() {
	*x = RedeemTokenRequest{}
	mi := &file_workspace_v1_registration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemTokenRequest) ProtoMessage() {}

func (x *RedeemTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_registration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemTokenRequest.ProtoReflect.Descriptor instead.
func (*RedeemTokenRequest) Descriptor() ([]byte, []int) {
	return file_workspace_v1_registration_proto_rawDescGZIP(), []int{0}
}

func (x *RedeemTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RedeemTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkspaceId   string                 `protobuf:"bytes,1,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,2,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedeemTokenResponse) Reset() {
	*x = RedeemTokenResponse{}
	mi := &file_workspace_v1_registration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedeemTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedeemTokenResponse) ProtoMessage() {}

func (x *RedeemTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workspace_v1_registration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedeemTokenResponse.ProtoReflect.Descriptor instead.
func (*RedeemTokenResponse) Descriptor() ([]byte, []int) {
	return file_workspace_v1_registration_proto_rawDescGZIP(), []int{1}
}

func (x *RedeemTokenResponse) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *RedeemTokenResponse) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

var File_workspace_v1_registration_proto protoreflect.FileDescriptor

const file_workspace_v1_registration_proto_rawDesc = "" +
	"\n" +
	"\x1fworkspace/v1/registration.proto\x12\fworkspace.v1\"*\n" +
	"\x12RedeemTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"W\n" +
	"\x13RedeemTokenResponse\x12!\n" +
	"\fworkspace_id\x18\x01 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"created_by\x18\x02 \x01(\tR\tcreatedBy2i\n" +
	"\x13RegistrationService\x12R\n" +
	"\vRedeemToken\x12 .workspace.v1.RedeemTokenRequest\x1a!.workspace.v1.RedeemTokenResponseBFZDgithub.com/tiwazs/gnosis-workspace/app/grpc/workspace/v1;workspacev1b\x06proto3"

var (
	file_workspace_v1_registration_proto_rawDescOnce sync.Once
	file_workspace_v1_registration_proto_rawDescData []byte
)

func file_workspace_v1_registration_proto_rawDescGZIP() []byte {
	file_workspace_v1_registration_proto_rawDescOnce.Do(func() {
		file_workspace_v1_registration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workspace_v1_registration_proto_rawDesc), len(file_workspace_v1_registration_proto_rawDesc)))
	})
	return file_workspace_v1_registration_proto_rawDescData
}

var file_workspace_v1_registration_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_workspace_v1_registration_proto_goTypes = []any{
	(*RedeemTokenRequest)(nil),  // 0: workspace.v1.RedeemTokenRequest
	(*RedeemTokenResponse)(nil), // 1: workspace.v1.RedeemTokenResponse
}
var file_workspace_v1_registration_proto_depIdxs = []int32{
	0, // 0: workspace.v1.RegistrationService.RedeemToken:input_type -> workspace.v1.RedeemTokenRequest
	1, // 1: workspace.v1.RegistrationService.RedeemToken:output_type -> workspace.v1.RedeemTokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_workspace_v1_registration_proto_init() }
func file_workspace_v1_registration_proto_init() {
	if File_workspace_v1_registration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workspace_v1_registration_proto_rawDesc), len(file_workspace_v1_registration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workspace_v1_registration_proto_goTypes,
		DependencyIndexes: file_workspace_v1_registration_proto_depIdxs,
		MessageInfos:      file_workspace_v1_registration_proto_msgTypes,
	}.Build()
	File_workspace_v1_registration_proto = out.File
	file_workspace_v1_registration_proto_goTypes = nil
	file_workspace_v1_registration_proto_depIdxs = nil
}
